# Generated by Django 5.2 on 2026-02-18
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("asset_type", models.CharField(choices=[("FCI", "FCI"), ("BOND", "BONO/ON"), ("STOCK", "ACCIÓN"), ("FX", "FX"), ("CASH", "EFECTIVO"), ("CRYPTO", "CRYPTO"), ("OTHER", "OTRO")], default="FCI", max_length=12)),
                ("currency", models.CharField(default="ARS", max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("base_currency", models.CharField(choices=[("ARS", "ARS"), ("USD", "USD"), ("EUR", "EUR")], default="ARS", max_length=3)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("preset", models.CharField(choices=[("CONS", "Conservador"), ("BAL", "Balanceado"), ("AGR", "Agresivo")], default="BAL", max_length=4)),
                ("virtual_cash", models.DecimalField(decimal_places=2, default=1000000, max_digits=18)),
                ("current_day", models.IntegerField(default=0)),
                ("seed", models.IntegerField(default=12345)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("severity", models.CharField(choices=[("LOW", "Baja"), ("MED", "Media"), ("HIGH", "Alta")], default="LOW", max_length=8)),
                ("title", models.CharField(max_length=140)),
                ("rationale", models.TextField()),
                ("evidence", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("OPEN", "Abierta"), ("ACCEPTED", "Aceptada"), ("IGNORED", "Ignorada")], default="OPEN", max_length=10)),
                ("decision_note", models.CharField(blank=True, max_length=240)),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.portfolio")),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tx_type", models.CharField(choices=[("BUY", "COMPRA"), ("SELL", "VENTA"), ("DEPOSIT", "DEPÓSITO"), ("WITHDRAW", "RETIRO"), ("DIVIDEND", "RENDIMIENTO/DIVIDENDO"), ("FEE", "COMISIÓN/GASTO")], max_length=10)),
                ("quantity", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("price", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("fee", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("tx_date", models.DateField(default=django.utils.timezone.localdate)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.asset")),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.portfolio")),
            ],
        ),
        migrations.CreateModel(
            name="SimPosition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=32)),
                ("quantity", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("avg_price", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("simulation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.simulation")),
            ],
            options={"unique_together": {("simulation", "symbol")}},
        ),
        migrations.CreateModel(
            name="SimTrade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=32)),
                ("side", models.CharField(choices=[("BUY", "BUY"), ("SELL", "SELL")], max_length=4)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("price", models.DecimalField(decimal_places=6, max_digits=18)),
                ("day", models.IntegerField(default=0)),
                ("simulation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.simulation")),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=40)),
                ("ip_address", models.CharField(blank=True, max_length=64, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=400)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
