# Generated by ChatGPT for InvPanel-Pro v11.2 on 2026-02-22
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_recommendation_ai_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="ai_action",
            field=models.CharField(max_length=12, blank=True, default="HOLD"),
        ),
    ]
